### ISSUE TITLE
Add new Team Members pictures and bios

### ISSUE THREAD

**Issue by pyjavo** [piensa/piensa.github.io#12]
Add new pictures to website.
- [x] Lennin
- [x] Wayner

Remove the following:
- [x] Javier
- [x] Gerson

**Comment by pyjavo** [comment]
Also should improve the `listing authors section` with this loop in index.html (Once all users and photos are created)

```
{% for author in site.authors %}
  {{ author[1].name }} -- {{ author[1].email }}
{% endfor %}
```

**Comment by ingenieroariel** [comment]
@gsolat let's get this done this week if possible.

**Comment by gsolat** [comment]
Ok, @ingenieroariel can we use your cam?

@Lenninlasd we need you to write a professional profile, please see the website to get a better idea of what the requirement is about.

**Comment by Lenninlasd** [comment]
@gsolat Got it
