### ISSUE TITLE
Javascript error when scrolling down

### ISSUE THREAD

**Issue by pyjavo** [piensa/piensa.github.io#37]
Javascript error when scrolling down in the home page:

```
Uncaught Error: Syntax error, unrecognized expression: /blog/
```

<img width="1279" alt="captura de pantalla 2016-08-30 a las 3 52 26 p m" src="https://cloud.githubusercontent.com/assets/3085051/18106545/d48c8cec-6ec9-11e6-9724-98a8771ffc9f.png">

**Comment by gsolat** [comment]
Hecho.
