### ISSUE TITLE
Menu and text get confusing when scrolling down

### ISSUE THREAD

**Issue by ingenieroariel** [piensa/piensa.github.io#5]
<img width="395" alt="screen shot 2016-04-13 at 10 15 26 am" src="https://cloud.githubusercontent.com/assets/54999/14498652/c4e154ac-0160-11e6-964c-b9e3644a9bee.png">

**Comment by gsolat** [comment]
![screenshot from 2016-04-13 15 03 24](https://cloud.githubusercontent.com/assets/5114135/14507620/1353b6e8-0189-11e6-9894-77269276e83a.png)
