### ISSUE TITLE
Blog section

### ISSUE THREAD

**Issue by pyjavo** [piensa/piensa.github.io#7]
I think there should be a blog in Piensa's website, so we can promote the website using quality content.

**Comment by ingenieroariel** [comment]
Let's look into using Medium for the blog.

**Comment by pyjavo** [comment]
Thought we were going to use jekyll? I think there are pros and cons about using Medium. 

**Pros**
- I think it will be easy to set it up so we can start writing posts
- No need to learn markdown (like when you use jekyll). A non-technical person won't need to know/learn markdown to write posts.

**Cons** 
- Using Medium will not be a good option for SEO ( The domain name medium.com will receive most of the traffic, and not piensa.co)
- Have to think of a workaround to redirect traffic from Medium web page to piensa.co

**Comment by pyjavo** [comment]
What do you think @gsolat ?

**Comment by ingenieroariel** [comment]
We can have blog.piensa.co be hosted at medium I think. Can we check?

**Comment by gsolat** [comment]
@javierdaza Una ventaja de hacer parte de una plataforma para publicar como Medium es la posibilidad de generar más tráfico de visitantes.
